### PR TITLE
Update Huion configs

### PR DESCRIPTION
**Pull request by X9VoiD**
# Changes
* Added Huion tablets
    * Gaomon S56K
    * Huion HS611
    * Huion 420
    * Inspiroy Q11K
* 9580:109 Initialization

### CODE REVIEW

**Comment by X9VoiD** [comment]
The initialization from TD for H420 is not working so we have to retrieve it from a usb packet capture

**Comment by X9VoiD** [comment]
Huion 420 and H420 requires explicit endpoint selection

**Comment by X9VoiD** [comment]
PR is ready and 420/H420 support may be pushed for later

**Comment by X9VoiD** [comment]
Made some follow-up changes for Huion HS lineup

Index 201 for those models vary from device to device of the same model, more information from 42a3243855dd76812a3c9c4c0a94aed39095426b

**Comment by InfinityGhost** [comment]
Is this ready to merge?

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
