### PR TITLE
Updated H610 Pro V2 configuration

### PR DESCRIPTION
**Pull request by Mrcubix**
# Is this a 420? :

No

# Verification:

https://discord.com/channels/615607687467761684/615611007951306863/805564430003339346

https://www.amazon.ca/dp/B00GWYYXV0

### CODE REVIEW

**Review by InfinityGhost — APPROVED** [review]

**Comment by InfinityGhost** [comment]
Appears to not include auxiliary support based on the config, can we get that supported?

**Comment by X9VoiD** [comment]
This shouldn't be named `V2` as it has the same device string identifier. We have a lot of other configurations with PID 109 and 110 merged into a single one since they don't really differ. For something to be V2 for Huions it has to be different in some other way like device string.

**Review by InfinityGhost — CHANGES_REQUESTED** [review]
We need to find some sort of other identifier to avoid configuration conflicts.

**Comment by X9VoiD** [comment]
Oh, I thought it added a new configuration with `V2`. My bad, this is fine.

**Comment by InfinityGhost** [comment]
> Oh, I thought it added a new configuration with `V2`. My bad, this is fine.

.

**Review by InfinityGhost — APPROVED** [review]
pepega

**Pull request merged**
