### PR TITLE
Fix Intuosv3 aux buttons

### PR DESCRIPTION
**Pull request by AbstractQbit**
Fixed parsed index of IntuosV3 devices

### CODE REVIEW

**Comment by InfinityGhost** [comment]
IIRC this issue is only present when using the Wacom driver, correct?

**Comment by AbstractQbit** [comment]
No, it tries to read buttons from the same byte that report parser uses for switching, that happens regardless of skip byte

**Comment by InfinityGhost** [comment]
Gotcha, so good to merge now?

**Comment by AbstractQbit** [comment]
Yeah, will need to move to having dynamic button count eventually, but for now this should work

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
