### PR TITLE
Add Device String Reader window to UX

### PR DESCRIPTION
**Pull request by X9VoiD**

### CODE REVIEW

**Comment by InfinityGhost** [comment]
Is this ready for merging?

**Comment by X9VoiD** [comment]
Yes, this is ready for merge

**Comment by InfinityGhost** [comment]
Appears to break after the first string is called.

**Comment by InfinityGhost** [comment]
Now I can't reproduce that deadlock, I think it might be a good idea to add a timeout to avoid that.

**Comment by X9VoiD** [comment]
Timeout added

**Review by InfinityGhost — APPROVED** [review]
Looks good.

**Pull request merged**
