### PR TITLE
Fix OutputReportLength of VEIKK S640

### PR DESCRIPTION
**Pull request by X9VoiD**
Not sure how I missed that before on the first PR for VEIKKs

### CODE REVIEW

**Comment by InfinityGhost** [comment]
Is this really necessary?

**Comment by X9VoiD** [comment]
Yes, this is so that OTD will send the OutputInitReport to the correct endpoint

**Comment by InfinityGhost** [comment]
We'll update output init report lengths where it is actually needed, how about that?

**Comment by X9VoiD** [comment]
Updated the PR to only change S640 where the change is needed.

**Comment by InfinityGhost** [comment]
lg2m now

**Pull request merged**
