### PR TITLE
Filter synthetic reports

### PR DESCRIPTION
**Pull request by X9VoiD**
Filter synthetic reports for binding handler and future extensions of `HandleReport()` through ReportHandled event.

### CODE REVIEW

**Comment by InfinityGhost** [comment]
I really don't like this change as a whole, I'd rather we just filter it on `BindingHandler.HandleBinding()`

**Comment by X9VoiD** [comment]
We can't because BindingHandler is static

**Comment by InfinityGhost** [comment]
> We can't because BindingHandler is static

?
```cs
public static void HandleBinding(TabletState tablet, IDeviceReport report)
{
    if (tablet == null || report is ISyntheticReport)
        return;

    if (report is ITabletReport tabletReport && tablet.Digitizer.ActiveReportID.IsInRange(tabletReport.ReportID))
        HandlePenBinding(tablet.Digitizer, tabletReport);
    if (report is IAuxReport auxReport)
        HandleAuxBinding(auxReport);
}
```

**Comment by X9VoiD** [comment]
That will block pressure reports coming from interp.

**Comment by InfinityGhost** [comment]
All this PR is doing is attaching HandleBinding to an unnecessary event. This would do exactly what you want.
```diff
diff --git a/OpenTabletDriver.Desktop/DesktopDriver.cs b/OpenTabletDriver.Desktop/DesktopDriver.cs
index d866543..f2c3cd7 100644
--- a/OpenTabletDriver.Desktop/DesktopDriver.cs
+++ b/OpenTabletDriver.Desktop/DesktopDriver.cs
@@ -10,9 +10,9 @@ namespace OpenTabletDriver.Desktop
     {
         protected override PluginManager PluginManager => AppInfo.PluginManager;
 
-        public override void HandleReport(IDeviceReport report)
+        protected override void ReadReport(IDeviceReport report)
         {
-            base.HandleReport(report);
+            base.ReadReport(report);
             BindingHandler.HandleBinding(Tablet, report);
         }
 
diff --git a/OpenTabletDriver/Driver.cs b/OpenTabletDriver/Driver.cs
index 00de8cb..b24f9ed 100644
--- a/OpenTabletDriver/Driver.cs
+++ b/OpenTabletDriver/Driver.cs
@@ -274,7 +274,12 @@ namespace OpenTabletDriver
         {
             if (EnableInput && OutputMode?.Tablet != null)
                 if (Interpolators.Count == 0 || (Interpolators.Count > 0 && report is ISyntheticReport) || report is IAuxReport)
-                    OutputMode.Read(report);
+                    ReadReport(report);
+        }
+
+        protected virtual void ReadReport(IDeviceReport report)
+        {
+            OutputMode.Read(report);
         }
     }
 }

```

**Comment by X9VoiD** [comment]
Thought we could use the event for reporting interpolated hertz to UX's tablet debugger, but yeah that will do

**Comment by InfinityGhost** [comment]
Would prefer to not do that in the tablet debugger, it is intended for raw data from the tablet without manipulation.

**Comment by X9VoiD** [comment]
I meant as a separate thing. Something like tablet report rate and output report rate

**Comment by InfinityGhost** [comment]
> I meant as a separate thing. Something like tablet report rate and output report rate

Maybe, but that's out of the scope of this PR.

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
