### PR TITLE
Detect when a type implements a generic interface of OpenTabletDriver…

### PR DESCRIPTION
**Pull request by X9VoiD**
….Plugin

XP Pen ReportParser

### CODE REVIEW

**Comment by X9VoiD** [comment]
Without Patch Type Count: 414
With Patch Type Count: 423

Without Patch

**Comment by InfinityGhost** [comment]
I actually just fixed this with 0e65b6209aa31a258ce66637f5bdfcc58ffc88ca lol

**Comment by X9VoiD** [comment]
lmao, should close this one then?

**Comment by InfinityGhost** [comment]
> lmao, should close this one then?

Test my changes first, but on my end `Types` now includes others like `XP_PenReportParser`

**Comment by X9VoiD** [comment]
Will test

**Comment by X9VoiD** [comment]
Yep works fine on my end too

**Comment by InfinityGhost** [comment]
We'll go ahead and close this in that case.

**Pull request closed without merging**
